- .github/workflows/mcvs-pr-validation.yml
This PR will add the PR validation action that will validate if a PR contains a description.
> build: [#58] Add PR validation action

- action.yml
Prevent duplication by merging unit & integration test and include integration test in code coverage as well.
> build(fix): [#69] Merge unit and integration test code coverage

- Taskfile.yml
- action.yml
Code coverage report was accidentally removed in previous PR.
> fix: Code coverage report missing

- Taskfile.yml
Clarify how to resolve two different code coverage issues when the pipeline fails.
> fix: [#115] Clarify remediation steps for resolving code-coverage issues in pipeline

- Taskfile.yml
Run https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck to check for vulnerabilities in the go code.
> feat: Add govulncheck install and run

- .github/dependabot.yml
Dependabot group updates to save time
> build: Dependabot group updates to save time

- README.md
Update README to include new timeout parameters for linting, testing and coverage
> docs: [#176] Update README to include new timeout parameters for linting, testing and coverage

- Taskfile.yml
Install go-swagger to ensure that one can create a swagger-client if a project provides a swagger API.
> feat: [#183] Install go-swagger v0.31.0

- .github/workflows/taskfile-sorted-units.yml
- Taskfile.yml
Guard that the elements in Taskfile units are sorted.
> build: [#181] Taskfile units should be sorted

- .github/workflows/taskfile-without-empty-lines.yml
- Taskfile.yml
* Guard populated lines in Taskfile.yml.
* Remove empty lines in Taskfile.yml to fix pipeline.
> fix: [#192] Ensure that there are NO empty lines in the Taskfile.yml

- action.yml
Closes https://github.com/schubergphilis/mcvs-golang-action/issues/222
> feat: made go-version-file configurable

- action.yml
fixed `go-version-file` variable call
> fix: inputs.go-version-file

- action.yml
Ensure that conventional commits is enforced to ensure that proper change logs can be created.
> feat: Lint commit using commitlint-github-action

- Taskfile.yml
* Remove replicated code from coverage and coverage-visual unit.
> fix: Code report generation duration

- action.yml
- commitlint.config.mjs
* Manage commit lint config centrally.
* Omit action as it caused to many challenges.
> fix: Run commitlint directly as the action contains too many issues

- build/task.yml
internal dir was omitted from code coverage
> fix: internal dir omitted from code coverage

- .github/dependabot.yml
- .github/workflows/golang.yml
- .github/workflows/gomod-go-version-updater.yml
- .gitignore
- README.md
- Taskfile.yml
- action.yml
- build/task.yml
- go.mod
* exit 1 if branch is behind main
* exit 1 if main has been merged into a branch
* to keep a git log clean which will help to find quicker what has been changed and why which will save time and money
> feat: git-lint

- README.md
Once merged, then do not run action again.
> fix: [#211] prevent run of action once merged into main

- .github/workflows/general.yml
- .github/workflows/golang.yml
- README.md
- action.yml
- build/task.yml
Run lint-git by using the general MCVS action.
> fix: use lint-git from general action

- .github/workflows/general.yml
- build/task.yml
Install another version of present if another version is defined.
> fix: install specific version of present

- README.md
- action.yml
- build/task.yml
Run `graphql-linter` using task and pipeline.
> feat: graphql-linter

- build/task.yml
Add a task to run [gqlgen](https://github.com/99designs/gqlgen) on for the `gqlgen.yml` files in your project.
> feat: add task to run gqlgen
