README.md, action.yml
* Enable govulncheck to check Golang vulnerabilities.
* Enforce a minimum code coverage. By default: 80 percent.
=> feat: [#48] Enable govulncheck and enforce minimum code coverage

README.md, action.yml, src/go-test.sh
* Run component tests.
* Enforce end user to update the expected code coverage if the actual exceeds it.
=> feat: [#65][#67][#71] Run component tests & ensure that expected code coverage threshold gets adjusted if actual exceeds it

src/go-test.sh
* Exclude files from code coverage.
* Prevent code duplication by reusing `go list`.
=> fix: [#85] Exclude files from go coverage

README.md, action.yml
* Optional GCI as some projects provide a different way of solving import issues.
* Avoid logging in to GHCR if public TrivyDBs are downloaded.
* Extended README to indicate that GCI is optional.
=> fix: [#87] Optional GCI

action.yml
* Ensure that 1 space is required before a comment in YAML as it conflicts with prettier (see coupled issue).
=> fix: [#89] Ensure that yamllint allows 1 space before a comment

action.yml
* It could be possible that a component test need to download docker images from a private registry.
=> fix: Allow use of GITHUB token for component test

README.md, action.yml
=> feat: [#55] Run steps in parallel to speed up CICD

action.yml
Golang version warning occurs due to missing if statement in govulncheck-action
=> fix: [#98] Golang version warning occurs due to missing if statement in govulncheck-action

Taskfile.yml
https://github.com/Yamashou/gqlgenc
If this will be bumped to a greater version in the future, endusers have to start using a newer version of the action.
=> feat: [#111] Allow consumers of this action to install gqlgenc version v0.25.4

Taskfile.yml
Currently, the suggestions are hardly readable. Adding this option shows the issues line by line which makes them easier to fix.
=> feat: [#113] Show golangci-lint suggestion line by line to facilitate fixing it

README.md, action.yml
* Use preserved TrivyDBs to prevent bump into rate limiting issues by default.
* Removed duplicated snippet from the table in the README by referring to the action.yml.
=> fix: [#117] Use preserved TrivyDBs from AWS ECR to prevent bump into rate limiting by default

Taskfile.yml
Use `{{.SED_INSERT_ADDITION}}` within the Taskfile that includes the remote to ensure that `sed -i` works on both Darwin and Linux machines.
=> fix: [#116] Sed addition for inserts if task run on a Darwin machine

README.md
Without TASK_X_REMOTE_TASKFILES task cannot include remote taskfiles.
=> fix: [#108] Ensure that task can include remote Taskfiles

Taskfile.yml
Install helm using script, but by avoiding the creation of a get_helm.sh script.
=> feat: [122] Install helm

Taskfile.yml
Allows users to issue `task remote:lint` as an alternative to `make lint`. This will prevent that one has to create individual mappings in each repository.
=> fix: Remote lint as alternative for make lint

Taskfile.yml
Mockery was not able to create mocks based on interfaces that reside in a build tagged integration and component files.
=> fix: Add missing build tags to mockery

README.md, Taskfile.yml
Update the README to include more information about Task and its usage.
Fixes #128
=> Add documentation for Task

README.md, Taskfile.yml
To allow the user of these tasks to specify their own sections, I've introduced the GCI_SECTIONS variable ~~(which is not defined on purpose)~~.
This also fixes the mismatch between the `gci` and `gci-write` tasks where the latter did specify sections and the former did not.
=> Allow user to customise gci sections

README.md
Without the `>-` task returns an error.
=> fix: Update an incorrect example in the README

CODEOWNERS
Add a code owners file to ensure default reviewers are added to PRs that get created
=> fix: Add a code owners file to ensure default reviewers are added to PRs that get created

Taskfile.yml
* Create constant for `~/go/bin/gci`.
* Install [Regal](https://github.com/StyraInc/regal) v0.29.2.
* Install [OPA](https://github.com/open-policy-agent/opa) v0.70.0.
* Run Regal and OPA using Task.
=> feat: [#137][#138][#140] Install Regal v0.29.2 and OPA v0.70.0 and run those tools using Task

Taskfile.yml
This includes writing `gofumpt` and `gofumpt-install` tasks.
The `format` task will:
- run (and install if needed) `gofumpt`
- run (and install if needed) `gci write`
- run `go mod tidy`
=> Add "format" task

CODEOWNERS, Taskfile.yml
Regal installation failed in GitHub runners as the installation fully relies in Mac.
Tests
=> fix: Install Regal on Linux

Taskfile.yml
This pull request introduces code coverage checks for the Open Policy Agent (OPA) policies. The feature ensures that policy testing maintains a minimum code coverage threshold and includes detailed reporting to explain the coverage results.
=> feat: [#143] OPA code coverage and include explanation feature

Taskfile.yml
This pull request includes changes to the `Taskfile.yml` to improve the handling of OPA tests by centralizing the OPA command into a variable. This change aims to simplify the command execution and make the script more maintainable.
Improvements to OPA test command handling:
* [`Taskfile.yml`](diffhunk://#diff-cd2d359855d0301ce190f1ec3b4c572ea690c83747f6df61c9340720e3d2425eR257-R263): Introduced a new variable `opa_cmd` to store the OPA test command and updated the script to use this variable for running tests, displaying explanations, and generating code coverage overview.
* JSON files have to be ignored to prevent "merge" errors while running OPA.
=> fix: Ignore JSON when running OPA as it only supports rego

Taskfile.yml
This pull request includes a new task to check if the `GOBIN` environment variable has been set in the `Taskfile.yml`. The most important change is the addition of a default task that runs this check.
New task addition:
* [`Taskfile.yml`](diffhunk://#diff-cd2d359855d0301ce190f1ec3b4c572ea690c83747f6df61c9340720e3d2425eR49-R60): Added a `default` task with a description and command to check whether `GOBIN` has been set by default, and a `check-gobin` task to perform the actual check and provide an error message if `GOBIN` is not set.
=> fix: [#147] Ensure that GOBIN is set to avoid assuming its value

README.md, action.yml
This pull request includes updates to the `README.md` and `action.yml` files to improve documentation and enhance the configuration of GitHub Actions for the project. The most important changes include the addition of a new input for downloading private Go modules, updates to the formatting of tables in the README, and changes to the environment variables used in the GitHub Actions workflow.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L55-R56): Improved formatting of tables and added a new option for `github-token-for-downloading-private-go-modules` in the list of variables. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L55-R56) …
=> fix: Lint and unit tests require a token sometimes for getting required binaries

Taskfile.yml, action.yml
This pull request includes changes to the `Taskfile.yml` and `action.yml` files to improve the handling of the `GOBIN` environment variable and streamline the task version check. The most important changes include adding conditional logic for `GOBIN` in GitHub Actions, updating task commands to echo `GOBIN`, and simplifying the task version check in the GitHub Action workflow.
Improvements to `GOBIN` handling:
* [`Taskfile.yml`](diffhunk://#diff-cd2d359855d0301ce190f1ec3b4c572ea690c83747f6df61c9340720e3d2425eR18-R22): Added conditional logic to set `GOBIN` to `/home/runner/go/bin` if running in GitHub Actions.
* [`Taskfile.yml`](diffhunk://#diff-cd2d359855d0301ce190f1ec3b4c572ea690c83747f6df61c9340720e3d2425eR178): Updated task commands to echo the value of `GOBIN` for better visibility …
=> fix: Omit ~/go/bin from task

README.md
Make GCI_SECTIONS variable readable in README.md.
=> build(fix): Make GCI_SECTIONS variable readable

README.md, Taskfile.yml, action.yml
Override:
* golangci-lint timeout as some projects take more time to complete the linting.
* override the build tag to ensure that specific kind of code, e.g. e2e, component can be checked.
=> fix: Extend timeout golangci-lint to default 3min with the ability to override it and override build-tag

Taskfile.yml
gci and other commands failed locally as gobin was not set in the context of Taskfile is this is set as an env on the machine.
=> fix: Ensure that GOBIN is set in the context of the Taskfile

action.yml
This pull request includes formatting and conditional logic improvements in the `action.yml` file. The most important changes include reformatting the `if` conditionals for better readability and adding a new testing type.
Formatting improvements:
* Reformatted the `if` conditionals to use multiline format for better readability in the `runs:` section.
Conditional logic enhancements:
* Added a new testing type `mcvs-texttidy` to the `if` conditionals for the `install task` step.
=> fix: Install task otherwise mcvs-texttidy cannot be run

Taskfile.yml
The existing linter does not work in projects that use version golang 1.24.0.
=> fix: Update golangci-lint to 1.64.2

Taskfile.yml, action.yml
the following commands were timing out
- golangci-lint run 
- test: integration
- coverage
I increased the timeout to 9 minutes
This happened when I introduced sbom generation, in mcvs-saas 
https://github.com/schubergphilis/mcvs-scanner/pull/775
We might have to increase the compute size of the runner somewhere in the future.
=> fix: Increase timeout otherwise testing, listing & coverage fail

Taskfile.yml
Supported [config](https://vektra.github.io/mockery/v2.52/configuration/#parameter-descriptions) parameters.
=> fix: [#178] Omit unsupported Mockery parameter output

README.md, Taskfile.yml, action.yml
* Update `task` version to 3.41.0.
* Let pipeline fail if there is a MCVS-golang-action version discrepancy between workflow and local Taskfile.
* Ensure that local task version is identical to remote.
* Setting GOBIN should be done before running GCI otherwise /gci stat not found will occur.
* Running remote task fails due to missing values for TIMEOUT variables that were introduced in another PR.
* Prevent that pipeline will fail if Dependabot updates the MCVS-golang-action version otherwise it could never update it.
=> fix: [#107] Keep version action in sync with the one in local Taskfile

Taskfile.yml
Previous message was generic and was not helpful for users of this action to resolve issues.
=> docs: [#190] Clarified the unclear: 'failed to extract version' message

Taskfile.yml
- Changed the variable used in the condition of the var `SED_INSERT_ADDITION`, to be `OS_COMMAND_TYPE` 
- Previous variable `OS_COMMAND` had wrong value `uname`
=> fix: [#197] wrong var for sed insertion condition

Taskfile.yml, action.yml
* Change default logging to normal.
* Introduce `-cicd` option to keep using verbose logging for CICD to ensure that developer can easily find the issue if a pipeline fails.
=> fix: [#195] Change logging tests to normal to improve developer experience

Taskfile.yml, action.yml
If task is installed using brew then the v is omitted.
=> fix: [#199] Keep task update to date unit broken if user installed task using brew

Taskfile.yml
Related to https://github.com/schubergphilis/mcvs-golang-action/issues/199. If users are using brew to install task, an exit 1 was thrown as v is omitted from the version that is installed using brew. To prevent additional issues in the near future, throw a warning instead of an exit 1.
* Show warning that indicates that user should update task.
* Sleep of three seconds to ensure that use is aware of the warning.
=> fix: [#203] Instead of throwing an exit 1 if task version differs show a warning to improve the user experience

README.md, action.yml
since the coverage is using test under the hood, the test timeout should also affect the coverage task command
=> fix: update code coverage timeout input to use test timeout variable

action.yml
it seems that multiline scripts do not work for the if clause. I fixed it by writing everything in one line
here's proof that it works with the mcvs-scanner repo
https://github.com/schubergphilis/mcvs-scanner/actions/runs/13785080013/job/38551097469
=> fix: remove \ from the if value and write the script on one line

action.yml
There's a new version of task available. See links below for the changelogs:
- [v3.42.0 - 2025-03-08](https://taskfile.dev/changelog/#v3420---2025-03-08)
- [v3.42.1 - 2025-03-10](https://taskfile.dev/changelog/#v3421---2025-03-10)
=> build(deps): Update the default version of Task

action.yml
require testing to run as well before assets are added to the release
=> fix: [#210] Adjust behavior that assets are added to a release before testing completion

Taskfile.yml
* Make major versions dynamic to ensure that one only have to override a version instead of setting a second var as well.
* GCI skip-generated to default as some projects are omitting it.
=> fix: Omit major versions while installing versions and add GCI skip-generated to default as some projects are omitting it

Taskfile.yml
Currently, a user of this action could bump into remote Taskfile version is not in sync locally and then the users is forced to up date it. To prevent that the user is forced, the user will be notified by a warning which is more user friendly.
=> fix: [#225] Show warning if remote taskfile version used locally is out of date

Taskfile.yml
* Only check if Taskfile and golang action are referring to the right remote file if they are present in a repository.
=> fix: [#215] Optional keep up to date checks if Taskfile and golang workflows are present

Taskfile.yml
* Running `mockery` will suffice if one has a .mockery.yaml in a project.
* Updated the default mockery to v2.53.3 to prevent that one has to override the version in each project.
=> fix: Make mock-generate deprecated and introduce mocks as the new way of generating mocks

README.md, action.yml
* The current grype v0.87.0 contains high findings. Update it to remediate the issues.
* Apparently, no markdown linter auto formatter was used by previous committer causing the changes in the README.md.
=> fix: Ensure that grype version can be updated as the current default contains high vulnerabilities

action.yml
* Other steps should run in parallel to speed up the build.
=> fix: Only build and release if release-dir input parameter is non-empty

Taskfile.yml
- Bump golangci-lint to `v2.0.1`
- Add new golangci-lint fmt comand
=> Bump golangci-lint to v2.0.1

action.yml
Let pipeline if if go mod is outdated to ensure that the go mod is up to date always as it is a security best practice to only use the modules that are in use.
=> fix: [#217] Exit 1 if go mod not up to date

build/task.yml
* When task remote:test-integration-cicd was run, one expected to see verbose log. As that did not happen it turned out that the TEST_TAGS was not propagated.
=> fix: test-cicd not working as expected due to not propagated TEST_TAGS var

action.yml
Version 3.43.3 was released a while ago. Time to bump the default version here as well.
=> build(deps): bump Task from 3.42.1 to 3.43.3

action.yml
GOBIN was not set when mocks-tidy was run as setup-go was omitted.
=> build(fix): task not found when mocks-tidy is run as setup-go sets gobin

build/task.yml
* To ensure that ctrl + click to navigate to file with insufficient code coverage will work.
Previous:
```
github.com/schubergphilis/mcvs-scanner/internal/pkg/data/dataset/dataset_helper.go:447:                                        insertFooPlatform                               83.3%
github.com/schubergphilis/mcvs-scanner/internal/pkg/data/dataset/dataset_helper.go:459:                                        insertFooPlatformsAdditional                    0.0%
```
After merging this PR:
```
internal/pkg/data/dataset/dataset_helper.go:447:                                        insertFooPlatform                               83.3%
internal/pkg/data/dataset/dataset_helper.go:459:                                        insertFooPlatformsAdditional                    0.0%
```
Ctrl + click …
=> fix: ctrl + click to file to increase code coverage

.github/workflows/golang.yml, Taskfile.yml
Use 3.1.0 action as lint-git branch does not exist anymore.
=> build: use action 3.1.0

.github/workflows/general.yml, .github/workflows/golang.yml, README.md, action.yml, configs/commitlint.config.mjs
Move to [mcvs-general-action](https://github.com/schubergphilis/mcvs-general-action/pull/7) as lint-commit is a general action.
=> build: move lint-commit to general action

action.yml
Version 3.44.0 was released on June 9th. Time to bump the version we use.
=> build(deps): bump Task from 3.43.3 to 3.44.0

README.md, action.yml
* Release OS darwin binaries to ensure binaries can be run on Darwin.
* Set version when building binaries using `ldflags`. Note: installed binaries using `go install` while show the buildInfo, but binaries require a version that is baked into the binary.
=> feat: release os darwin binaries

.golangci.yml, build/task.yml
* noinlineerr
* wsl replaced by wsl_v5
Update `.golangci.yml` snippet as follows:
```
linters:
default: all
disable:
- wsl
```
=> build: bump golangci-lint to v2.2.2

action.yml
Task version 3.44.1 was released on July 23rd. Time to bump our default version.
=> build(deps): bump Task from 3.44.0 to 3.44.1

.github/workflows/package-version-updater.yml, README.md, build/task.yml, scripts/package-version-updater.sh
Some package versions cannot be updated by Dependabot therefor another process is required to update them on a weekly basis. Note: some default package versions have been removed in this PR as well as the end users have to use the versions that will be set by the package-updater.
=> build: [#308] update packages that are not updated by dependabot
